name: pd
channels:
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12
  - appdirs=1.4.4
  - arrow=1.2.2
  - astroid=2.6.6
  - atomicwrites=1.4.0
  - attrs=21.4.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - black=19.10b0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cookiecutter=1.7.3
  - cryptography=36.0.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.4
  - flake8=3.9.2
  - icu=58.2
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jedi=0.18.1
  - jinja2=3.0.3
  - jinja2-time=0.2.0
  - joblib=0.17.0
  - jpeg=9d
  - jsonschema=4.4.0
  - jupyter_client=6.1.12
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - keyring=23.4.0
  - lazy-object-proxy=1.6.0
  - libpng=1.6.37
  - libspatialindex=1.9.3
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.11
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - nltk=3.5
  - numpydoc=1.2
  - openssl=1.1.1h
  - packaging=21.3
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - pluggy=1.0.0
  - poyo=0.5.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygments=2.11.2
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pynacl=1.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - regex=2022.3.15
  - requests=2.27.1
  - rope=0.22.0
  - rtree=0.9.7
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sphinx=4.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlite=3.38.2
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss=0.4
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.50.2
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - ujson=5.1.0
  - unidecode=1.2.0
  - urllib3=1.26.8
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - wrapt=1.12.1
  - yaml=0.2.5
  - yapf=0.31.0
  - zipp=3.7.0
  - zlib=1.2.12
  - pip:
    - altair==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - backports-zoneinfo==0.2.1
    - blinker==1.4
    - cachetools==5.0.0
    - filelock==3.6.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - huggingface-hub==0.5.1
    - ipywidgets==7.7.0
    - jupyterlab-widgets==1.1.0
    - notebook==6.4.10
    - numpy==1.21.6
    - pandas==1.3.5
    - pdfminer-six==20211012
    - pdfplumber==0.6.0
    - pillow==9.1.0
    - prometheus-client==0.14.1
    - protobuf==3.20.0
    - pyarrow==7.0.0
    - pydeck==0.7.1
    - pympler==1.0.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywinpty==2.0.5
    - sacremoses==0.0.49
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - semver==2.13.0
    - send2trash==1.8.0
    - sentence-transformers==2.2.0
    - sentencepiece==0.1.96
    - smmap==5.0.0
    - streamlit==1.8.1
    - terminado==0.13.3
    - threadpoolctl==3.1.0
    - tokenizers==0.12.1
    - toolz==0.11.2
    - torch==1.11.0
    - torchvision==0.12.0
    - transformers==4.18.0
    - tzdata==2022.1
    - tzlocal==4.2
    - validators==0.18.2
    - wand==0.6.7
    - widgetsnbextension==3.6.0
